#!/usr/bin/env python3

import datetime

def get_some_data():
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    return some_data = ['b', 'one', 0b1, 0xb, 11, 0o0, 0, 1, 0xb == 11, "T", 'Two "quotes", an apostrophe \' and a backslash \\', None, 3.14, False, 'F', 2020-11-17', now]


